### ISSUE TITLE
Talk about using ATSynedit

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#239]
@srd-software
Here we can talk.

**Comment by Alexey-T** [comment]
Install .lpk package from https://github.com/Alexey-T/ATFlatControls
    Install package from https://github.com/Alexey-T/ATSynEdit
    open ATSynedit/app/demo_editor, it is enough to show editor.

**Comment by srd-software** [comment]
Yep, I had the basic editor working, that was easy (as long as that's all I make work!). I made a small app with lazarus using the atsynedit and it works OK, added file dropping and all OK. So I have it working. 

As far as getting that from lazarus to delphi, I've not looked into that much. I'm guessing it's a matter of making a package in delphi, adding the existing files, then working through the resulting errors?

**Comment by Alexey-T** [comment]
Yes - but Lot of resulting errors. Lazarus version uses such units as lclintf, lclproc, lcltype, etc

**Comment by srd-software** [comment]
Yes, lots of IDE incompatibilities for sure. I looked at it this morning just to get a feel for it. I'll see what I can do with.

**Comment by Alexey-T** [comment]
I want to sell it for Delphi users. you will get 30% of that.

**Comment by srd-software** [comment]
That would be great but I'd have to get it to work first! And there's a lot going on under the hood. 

Speaking of which, here's a question for you. Are you wanting to try and keep the PAS code for both lazarus and delphi in the same files (using conditionals to separate them)? Or are you going to separate them into 2 different components?

**Comment by Alexey-T** [comment]
I need separate repository, which is PRIVATE on github. So it will be closed source repo. (user can buy it for $.)

**Comment by Alexey-T** [comment]
It Delphi port can be compiled for Laz too, it is plus of course.

**Comment by srd-software** [comment]
OK. Long way from there now but good to know.

**Comment by srd-software** [comment]
I looked at all this file by file over the weekend and again this morning for quite some time. I don't think it's something I'll be able to do as it looks like there is SO much of the fpc rtl code that needs to be rewritten and I'm just not familiar enough with fpc. 

Have you thought about starting with the delphi synedit package (which the atsynedit appears to be based on?) and then adding your extended functions (i.e., synwrite and/or atsynedit functions) to that? At least you'd be starting off with a working delphi component. Then use what you've done in the synwrite app and/or atsynedit component as a guide to new functions? 

Been a long time since I looked at synedit so I downloaded the newest one and it looks like a good starting point...

**Comment by Alexey-T** [comment]
ATsynedit is written from scratch...

**Comment by srd-software** [comment]
Ah, OK. They have similar look so I wondered. Do you have delphi or just lazarus to work with?

**Comment by Alexey-T** [comment]
I have not much time to make Delphi port, so help needed.

**Comment by srd-software** [comment]
I looked at it all again today and there is just so much stuff in there to change! Maybe the best approach would be to start the delphi version from scratch as well. Comment out all the initial fcp files from "uses", but keep all the types, constants and vars you can. Comment out all the funcs, procs and properties so that they don't cause errors but are still "in there" to bring back one by one. 

That all may be more trouble than it's worth, but I'll attach a atsynedit pas file that I did this to. At least it compiles this way without errors and you could bring back pieces of it a little at a time. Note that I had to rename it with a txt extension to get it to upload here.

Unfortunately you know your own component so much better than anyone else I'm afraid you'd have to do most of the work! But maybe this idea will help.

BTW, the OptShowActiveMarkInverted property we (well, I) struggled with so much yesterday is working well, thanks!

Stan

[atsynedit.pas.txt](https://github.com/Alexey-T/ATSynEdit/files/3277153/atsynedit.pas.txt)

**Comment by Alexey-T** [comment]
So let’s just decline this work...

**Comment by srd-software** [comment]
Well, I don't see any easy or quick path to converting it so that might be best for now.
