### ISSUE TITLE
Too big coords and Cocoa IME

### ISSUE THREAD

**Issue by Alexey-T** [Alexey-T/ATSynEdit#318]
@rich2014
I fixed the function `calcBound` to consider TATPoint (int64) coordinates.

```
function TATAdapterCocoaIME.calcBound( var params: TCocoaIMEParameters ) : TRect;
var
  PntText1, PntText2: TPoint;
  PntCoord1, PntCoord2: TATPoint;
begin
  // two vertexs in chars
  PntText1:= _IntermediateTextBeginPos;
  PntText2:= PntText1;
  PntText1.X:= PntText1.X + params.selectedStart;
  PntText2.X:= PntText2.X + params.selectedLength;

  // two vertexs in pixels
  PntCoord1:= _editor.CaretPosToClientPos( PntText1 );
  PntCoord1.Y:= PntCoord1.Y - _editor.TextCharSize.Y div 2;

  PntCoord2:= _editor.CaretPosToClientPos( PntText2 );
  PntCoord2.Y:= PntCoord2.Y + _editor.TextCharSize.Y;

  // client rect in pixels
  Result.Left:= PntCoord1.X;
  Result.Top:= PntCoord1.Y;
  Result.Right:= PntCoord2.X;
  Result.Bottom:= PntCoord2.Y;
end; 
```

Int64 big values are happening when you open file with huge line, line of length about 2Gb (little smaller than 2Gb).

Can you check that Cocoa IME input works with huge line of length ~ 2G, at the end of the line?

**Comment by Alexey-T** [comment]
Test file can be made by a python script.
```
f=open('longline.log', 'w')
f.write('w'*0x7FFFFFF0+'\n---\n')
del f
```

**Comment by rich2014** [comment]
I will try it later.

but `_IntermediateTextBeginPos` is TPoint, do we need to consider the length of the selected text?

**Comment by Alexey-T** [comment]
`_IntermediateTextBeginPos` is getting value from CaretItem PosX/PosY - they are Longint (32-bit ) always.

**Comment by rich2014** [comment]
@Alexey-T 

hi, Alexey

from a technical perspective, `calcBound()` returns the correct result for `longline.log`.

but from a user perspective, the experience may be unacceptable.

1. the opening speed is very slow. however, among the several text editors i tested, it is already the fastest, which is barely acceptable.

2. the most terrible thing is that the typing speed is very, very slow. it takes minutes to type a character. of course, other editors are the same.

3. because it takes too long to insert characters, the IME pop-up window can't wait for the completion of inserting Intermediate text, and it has already popped up in the lower left corner, so the correct return of calcBound() is meaningless. of course, for other editors are the same.

4. and, in order to process `longline.log`, it takes up more than 20G of memory.

5. unless the processing of ultra-long lines is redesigned, the practicability of supporting ultra-long lines is not very strong, and users may think that the system crashes and misuse is very likely.
for example, it is designed that each line itself is also composed of a linked list. the initial size of each node is 16K. When editing, it can be operated on the corresponding node. nodes whose size exceeds 32K are split into two nodes.
however, there are too many places that need to be redesigned. it is recommended to limit the length of a line to 1000K characters, which should be a better balance.

6. 
only from a technical point of view, i'm still not sure whether `PntText1.X` will cause out of range longint. although the values of params.selectedStart and params.selectedLength are very small, `_IntermediateTextBeginPos.X` may be close to the limit of longint, and it may exceed longint after adding:
  PntText1.X:= PntText1.X + params.selectedStart;
  PntText2.X:= PntText2.X + params.selectedLength;

7. in addition, two related bugs of ATSynEdit were found.

**Comment by rich2014** [comment]
### bug 1: `Undo` fails when the line exceeds 102402 characters. 

this also affects the input of IME, because IME relies on UndoAndRedo.

**Comment by rich2014** [comment]
### Bug2: `Chinese` are displayed abnormally when the line exceeds 500 characters

Sample File: [sample.txt](https://github.com/Alexey-T/ATSynEdit/files/11471404/sample.txt)

Screen Recording:

https://github.com/Alexey-T/ATSynEdit/assets/102933068/f15d3f06-f14a-47c4-b5c8-4543f08e1059

**Comment by Alexey-T** [comment]
Thanks for testing. I guess I keep the current code and user must not use IME with huge lines.

bug 1: in CudaText, it is option "max_line_len_for_undo": 102400

bug 2: in CudaText, it is option "max_line_len_for_accurate_width": 500

**Comment by Alexey-T** [comment]
I don't plan to make storage of 16K nodes: too big redesign and hard work.

**Comment by rich2014** [comment]
even without IME, editing `longline.log` is still too slow to be useful.

maybe it is better to read only by default when encountering super long lines.

**Comment by Alexey-T** [comment]
Maybe file can have super long lines + usual lines. editing of usual lines will be ok. so read-only will be bad.
